'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("QB.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property burstlogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("burstlogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property CPU() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("CPU", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cryptoguru() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cryptoguru", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Download() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Download", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html lang=&quot;en&quot; &gt;
        '''
        '''&lt;head&gt;
        '''  &lt;meta charset=&quot;UTF-8&quot;&gt;
        '''  &lt;title&gt;Prism Loading Screen&lt;/title&gt;
        '''  &lt;style&gt;
        '''  body {
        '''  -webkit-font-smoothing: antialiased;
        '''  text-rendering: optimizeLegibility;
        '''  font-family: &quot;proxima-nova-soft&quot;, sans-serif;
        '''  -webkit-user-select: none;
        '''  overflow: hidden;
        '''}
        '''body .vertical-centered-box {
        '''  position: absolute;
        '''  width: 100%;
        '''  height: 100%;
        '''  text-align: center;
        '''}
        '''body .vertical-centered-box:after {
        '''  content: &apos;&apos;;
        '''  display: inline-block;
        '''  height: 100%;
        '''  vertical-al [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property loadscreen() As String
            Get
                Return ResourceManager.GetString("loadscreen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html lang=&quot;en&quot; &gt;
        '''
        '''&lt;head&gt;
        '''  &lt;meta charset=&quot;UTF-8&quot;&gt;
        '''  &lt;title&gt;Prism Loading Screen&lt;/title&gt;
        '''  &lt;style&gt;
        '''  body {
        '''  -webkit-font-smoothing: antialiased;
        '''  text-rendering: optimizeLegibility;
        '''  font-family: &quot;proxima-nova-soft&quot;, sans-serif;
        '''  -webkit-user-select: none;
        '''  overflow: hidden;
        '''}
        '''body .vertical-centered-box {
        '''  position: absolute;
        '''  width: 100%;
        '''  height: 100%;
        '''  text-align: center;
        '''}
        '''body .vertical-centered-box:after {
        '''  content: &apos;&apos;;
        '''  display: inline-block;
        '''  height: 100%;
        '''  vertical-al [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property stoppedscreen() As String
            Get
                Return ResourceManager.GetString("stoppedscreen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html lang=&quot;en&quot; &gt;
        '''
        '''&lt;head&gt;
        '''  &lt;meta charset=&quot;UTF-8&quot;&gt;
        '''  &lt;title&gt;Prism Loading Screen&lt;/title&gt;
        '''  &lt;style&gt;
        '''  body {
        '''  -webkit-font-smoothing: antialiased;
        '''  text-rendering: optimizeLegibility;
        '''  font-family: &quot;proxima-nova-soft&quot;, sans-serif;
        '''  -webkit-user-select: none;
        '''  overflow: hidden;
        '''}
        '''body .vertical-centered-box {
        '''  position: absolute;
        '''  width: 100%;
        '''  height: 100%;
        '''  text-align: center;
        '''}
        '''body .vertical-centered-box:after {
        '''  content: &apos;&apos;;
        '''  display: inline-block;
        '''  height: 100%;
        '''  vertical-al [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Stoppingscreen() As String
            Get
                Return ResourceManager.GetString("Stoppingscreen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property vps() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vps", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property vps_168_57() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vps_168_57", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
